name: ebook_reader_mobilapp
description: "An ebook reader application focused for android develepement."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  flutter_pdfview: 1.3.2
  epub_view: ^3.2.0
  file_picker: ^8.1.3
  shared_preferences: ^2.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: 0.9.2

flutter_icons:
  android: true,
  ios: true,
  image_path: assets/icons/books.png

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Italic-VariableFont_wght.ttf
          weight: 500
        - asset: fonts/Montserrat-VariableFont_wght.ttf
          weight: 700
