name: ebook_reader_mobilapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
    assets:
      - /assets/icons/
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

fonts:
  - family: Monsterrat
    fonts:
      - asset: fonts/Montserrat-Italic-VariableFont_wght.ttf
        weight: 500
      - asset: fonts/Montserrat-VariableFont_wght.ttf
        weight: 700

